//! End-to-End HFT Pipeline Integration Test
//!
//! Tests the full trading pipeline:
//!   SimulatedFeed → FeedManager → SignalEngine → WalletGuard → SimulatedExecution
//!
//! Validates signal-to-dispatch latency target (<1ms) and correctness
//! of risk checks, fills, and wallet state updates.

use clawdius_core::broker::execution::{ExecutionAdapter, Fill, SimulatedExecution};
use clawdius_core::broker::feeds::{MarketUpdate, SimulatedFeed};
use clawdius_core::broker::signal::{MarketData, Signal, SignalDirection, SignalEngine};
use clawdius_core::broker::strategy::Strategy;
use clawdius_core::broker::wallet_guard::{
    Order, OrderSide, RejectReason, RiskDecision, RiskParams, Wallet, WalletGuard,
};
use rust_decimal::Decimal;
use std::time::Instant;

// ─── Test Strategy ───────────────────────────────────────────────────────────

/// Strategy that generates a buy signal when price < threshold.
struct ThresholdBuyStrategy {
    name: String,
    threshold: Decimal,
}

impl ThresholdBuyStrategy {
    fn new(name: &str, threshold: f64) -> Self {
        Self {
            name: name.to_string(),
            threshold: Decimal::from_f64_retain(threshold).unwrap(),
        }
    }
}

impl Strategy for ThresholdBuyStrategy {
    fn evaluate(&self, market_data: &MarketData) -> Option<Signal> {
        if market_data.price < self.threshold {
            Some(Signal {
                symbol: market_data.symbol.clone(),
                direction: SignalDirection::Buy,
                confidence: 0.9,
                strategy: self.name.clone(),
                timestamp: market_data.timestamp,
            })
        } else {
            None
        }
    }

    fn name(&self) -> &str {
        &self.name
    }
}

/// Strategy that always generates a sell signal (for testing).
struct AlwaysSellStrategy {
    name: String,
}

impl Strategy for AlwaysSellStrategy {
    fn evaluate(&self, market_data: &MarketData) -> Option<Signal> {
        Some(Signal {
            symbol: market_data.symbol.clone(),
            direction: SignalDirection::Sell,
            confidence: 0.5,
            strategy: self.name.clone(),
            timestamp: market_data.timestamp,
        })
    }

    fn name(&self) -> &str {
        &self.name
    }
}

// ─── Pipeline Builder ────────────────────────────────────────────────────────

/// Order quantity to use for all generated orders.
const ORDER_QTY: u64 = 10;

/// Convert Signal to Order. Uses symbol name hash as u32 symbol ID
/// and mid-price * 100 as u64 price (cents).
fn signal_to_order(signal: &Signal, mid_price: u64) -> Order {
    // Deterministic symbol hash for u32 ID.
    let symbol_id = simple_hash(&signal.symbol) as u32;
    let side = match signal.direction {
        SignalDirection::Buy => OrderSide::Buy,
        SignalDirection::Sell => OrderSide::Sell,
        SignalDirection::Hold => return Order::new(symbol_id, OrderSide::Buy, 0, 1), // no-op
    };
    Order::new(symbol_id, side, ORDER_QTY, mid_price)
}

/// Simple deterministic string hash.
fn simple_hash(s: &str) -> u64 {
    let mut hash: u64 = 5381;
    for b in s.bytes() {
        hash = hash.wrapping_mul(33).wrapping_add(b as u64);
    }
    hash
}

/// Convert MarketUpdate::Quote to MarketData for signal engine.
fn quote_to_market_data(update: &MarketUpdate) -> Option<MarketData> {
    match update {
        MarketUpdate::Quote(q) => Some(MarketData {
            symbol: q.symbol.0.clone(),
            price: Decimal::from_f64_retain(q.bid).unwrap_or_default(),
            volume: Decimal::from(1000),
            timestamp: q.timestamp,
        }),
        MarketUpdate::Heartbeat => None,
    }
}

/// Extract mid-price from a MarketUpdate.
fn mid_price_from_update(update: &MarketUpdate) -> u64 {
    match update {
        MarketUpdate::Quote(q) => {
            let mid = (q.bid + q.ask) / 2.0;
            (mid * 100.0) as u64 // Convert to cents
        },
        MarketUpdate::Heartbeat => 0,
    }
}

// ─── Pipeline Execution ──────────────────────────────────────────────────────

/// Result of processing one market update through the full pipeline.
struct PipelineResult {
    /// Market update received.
    update: MarketUpdate,
    /// Signals generated by strategies.
    signals: Vec<Signal>,
    /// Risk decisions for each signal.
    decisions: Vec<RiskDecision>,
    /// Fills for approved orders.
    fills: Vec<Fill>,
    /// Time from receiving update to dispatching fills (nanos).
    signal_to_dispatch_ns: u64,
}

/// Run one market update through the full pipeline.
fn run_pipeline_step(
    feed: &SimulatedFeed,
    engine: &mut SignalEngine,
    guard: &WalletGuard,
    wallet: &Wallet,
    execution: &dyn ExecutionAdapter,
) -> PipelineResult {
    let start = Instant::now();

    // 1. Feed generates market data
    let update = feed.generate_quote();

    // 2. Convert to MarketData and feed to signal engine
    let mut signals = Vec::new();
    if let Some(market_data) = quote_to_market_data(&update) {
        signals = engine.process(&market_data);
    }

    // 3. Risk-check each signal → Order
    let mid = mid_price_from_update(&update);
    let mut decisions = Vec::new();
    let mut fills = Vec::new();

    for signal in &signals {
        let order = signal_to_order(signal, mid);
        let decision = guard.check(wallet, &order);
        decisions.push(decision);

        if let RiskDecision::Approve = decision {
            if let Ok(fill) = execution.submit_order(&order) {
                fills.push(fill);
            }
        }
    }

    let elapsed = start.elapsed().as_nanos() as u64;

    PipelineResult {
        update,
        signals,
        decisions,
        fills,
        signal_to_dispatch_ns: elapsed,
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn test_pipeline_end_to_end_happy_path() {
    // Setup: SimulatedFeed with AAPL at $150
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 150.0)]);

    // Setup: Signal engine with a buy-below-threshold strategy
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow200", 200.0)));

    // Setup: Wallet guard with generous limits
    let guard = WalletGuard::new(RiskParams {
        pi_max: 10_000,
        sigma_max: 1_000,
        lambda_max: 10_000_000,
        margin_ratio: 4,
    });

    // Setup: Wallet with sufficient cash
    let wallet = Wallet::new(100_000_000_00); // $1B in cents

    // Setup: Simulated execution
    let execution = SimulatedExecution::new();

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: Feed produced a quote
    assert!(matches!(result.update, MarketUpdate::Quote(_)));

    // Verify: Strategy generated a buy signal (price < threshold)
    assert_eq!(result.signals.len(), 1);
    assert_eq!(result.signals[0].direction, SignalDirection::Buy);

    // Verify: Risk check approved
    assert_eq!(result.decisions.len(), 1);
    assert_eq!(result.decisions[0], RiskDecision::Approve);

    // Verify: Order was executed
    assert_eq!(result.fills.len(), 1);
    assert_eq!(result.fills[0].quantity, ORDER_QTY);
    assert!(result.fills[0].price > 0);
}

#[test]
fn test_pipeline_rejects_over_limit_order() {
    // Setup: Feed with AAPL
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 150.0)]);

    // Setup: Strategy that always generates signals
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(AlwaysSellStrategy {
        name: "AlwaysSell".into(),
    }));

    // Setup: Guard with TINY position limit
    let guard = WalletGuard::new(RiskParams {
        pi_max: 5, // Only 5 units allowed
        sigma_max: 1_000,
        lambda_max: 10_000_000,
        margin_ratio: 4,
    });

    // Setup: Wallet with zero position
    let wallet = Wallet::new(100_000_000_00);

    // Setup: Execution
    let execution = SimulatedExecution::new();

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: Signal was generated
    assert_eq!(result.signals.len(), 1);

    // Verify: Risk check REJECTED (sell 10 units but pi_max = 5)
    assert_eq!(result.decisions.len(), 1);
    assert!(matches!(
        result.decisions[0],
        RiskDecision::Reject(RejectReason::PositionLimitExceeded { .. })
    ));

    // Verify: No fills
    assert_eq!(result.fills.len(), 0);
}

#[test]
fn test_pipeline_rejects_insufficient_margin() {
    // Setup: Feed with expensive symbol
    let feed = SimulatedFeed::with_symbols(&["TSLA"], &[("TSLA", 500.0)]);

    // Setup: Buy strategy
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow1000", 1000.0)));

    // Setup: Guard with margin ratio 1:1
    let guard = WalletGuard::new(RiskParams {
        pi_max: 10_000,
        sigma_max: 1_000,
        lambda_max: 10_000_000,
        margin_ratio: 1, // Full margin required
    });

    // Setup: Wallet with very little cash
    let wallet = Wallet::new(100); // $1.00 in cents

    // Setup: Execution
    let execution = SimulatedExecution::new();

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: Signal generated
    assert_eq!(result.signals.len(), 1);

    // Verify: Rejected for insufficient margin
    assert_eq!(result.decisions.len(), 1);
    assert!(matches!(
        result.decisions[0],
        RiskDecision::Reject(RejectReason::InsufficientMargin { .. })
    ));

    // Verify: No fills
    assert!(result.fills.is_empty());
}

#[test]
fn test_pipeline_execution_reject_all() {
    // Setup
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 150.0)]);
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow200", 200.0)));
    let guard = WalletGuard::with_defaults();
    let wallet = Wallet::new(100_000_000_00);

    // Setup: Execution in reject-all mode
    let execution = SimulatedExecution::new();
    execution.set_reject_all(true);

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: Signal generated and risk approved
    assert_eq!(result.signals.len(), 1);
    assert_eq!(result.decisions[0], RiskDecision::Approve);

    // Verify: No fills (execution rejected)
    assert!(result.fills.is_empty());
}

#[test]
fn test_pipeline_signal_to_dispatch_latency() {
    // Setup
    let feed = SimulatedFeed::with_symbols(
        &["AAPL", "GOOG", "MSFT"],
        &[("AAPL", 150.0), ("GOOG", 2800.0), ("MSFT", 400.0)],
    );
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow1000", 1000.0)));
    engine.register_strategy(Box::new(AlwaysSellStrategy {
        name: "AlwaysSell".into(),
    }));
    let guard = WalletGuard::with_defaults();
    let wallet = Wallet::new(100_000_000_00);
    let execution = SimulatedExecution::new();

    // Run 100 iterations and measure latency
    let iterations = 100;
    let mut max_ns: u64 = 0;
    let mut total_ns: u64 = 0;

    for _ in 0..iterations {
        let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);
        max_ns = max_ns.max(result.signal_to_dispatch_ns);
        total_ns += result.signal_to_dispatch_ns;
    }

    let avg_ns = total_ns / iterations;
    let max_us = max_ns / 1_000;
    let avg_us = avg_ns / 1_000;

    // SLO: signal-to-dispatch < 1ms (1,000,000 ns)
    assert!(
        max_ns < 1_000_000,
        "signal-to-dispatch SLO violated: max = {max_us}µs (limit: 1000µs)"
    );

    // Log for observability (visible in test output with --nocapture)
    eprintln!(
        "Pipeline latency: avg = {avg_us}µs, max = {max_us}µs (over {iterations} iterations)"
    );
}

#[test]
fn test_pipeline_slippage_applied() {
    // Setup
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 150.0)]);
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow200", 200.0)));
    let guard = WalletGuard::with_defaults();
    let wallet = Wallet::new(100_000_000_00);

    // Setup: Execution with 5-tick slippage
    let execution = SimulatedExecution::new();
    execution.set_slippage_ticks(5);

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: Fill includes slippage
    assert_eq!(result.fills.len(), 1);
    let mid = mid_price_from_update(&result.update);
    assert_eq!(result.fills[0].price, mid + 5);
}

#[test]
fn test_pipeline_no_signal_no_fill() {
    // Setup: Strategy that only buys below threshold, but feed price is above
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 500.0)]);
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow100", 100.0)));
    let guard = WalletGuard::with_defaults();
    let wallet = Wallet::new(100_000_000_00);
    let execution = SimulatedExecution::new();

    // Run pipeline
    let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);

    // Verify: No signals generated (price > threshold)
    assert!(result.signals.is_empty());
    assert!(result.decisions.is_empty());
    assert!(result.fills.is_empty());
}

#[test]
fn test_pipeline_multi_symbol() {
    // Setup: Multiple symbols with different strategies
    let feed = SimulatedFeed::with_symbols(&["AAPL", "GOOG"], &[("AAPL", 150.0), ("GOOG", 2800.0)]);
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow5000", 5000.0)));

    let guard = WalletGuard::with_defaults();
    let wallet = Wallet::new(100_000_000_00);
    let execution = SimulatedExecution::new();

    // Run multiple steps to cover different symbols
    let mut total_fills = 0usize;
    let mut total_signals = 0usize;

    for _ in 0..20 {
        let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);
        total_signals += result.signals.len();
        total_fills += result.fills.len();
    }

    // Verify: Some signals were generated and some fills executed
    assert!(
        total_signals > 0,
        "Expected at least some signals over 20 iterations"
    );
    assert!(
        total_fills > 0,
        "Expected at least some fills over 20 iterations"
    );
}

#[test]
fn test_pipeline_wallet_state_after_fill() {
    // This test demonstrates that the pipeline produces fills that
    // can be used to update wallet state (position tracking).
    let feed = SimulatedFeed::with_symbols(&["AAPL"], &[("AAPL", 150.0)]);
    let mut engine = SignalEngine::new();
    engine.register_strategy(Box::new(ThresholdBuyStrategy::new("BuyBelow200", 200.0)));
    let guard = WalletGuard::with_defaults();

    let mut wallet = Wallet::new(100_000_000_00);
    let execution = SimulatedExecution::new();

    // Run 5 steps, updating wallet after each fill
    for _ in 0..5 {
        let result = run_pipeline_step(&feed, &mut engine, &guard, &wallet, &execution);
        for fill in &result.fills {
            let delta = match fill.side {
                OrderSide::Buy => fill.quantity as i64,
                OrderSide::Sell => -(fill.quantity as i64),
            };
            wallet.update_position(fill.symbol, delta);
        }
    }

    // Verify: Wallet has a position in the AAPL symbol
    let aapl_id = simple_hash("AAPL") as u32;
    let position = wallet.position(aapl_id);
    assert!(
        position > 0,
        "Expected positive AAPL position, got {position}"
    );
}
