//! Signal Engine
//!
//! Processes market data through registered strategies to generate signals.

use super::ring_buffer::RingBuffer;
use super::strategy::Strategy;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// Market data for signal generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketData {
    /// Symbol
    pub symbol: String,
    /// Current price
    pub price: Decimal,
    /// Volume
    pub volume: Decimal,
    /// Timestamp (unix millis)
    pub timestamp: u64,
}

/// Trading signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Symbol to trade
    pub symbol: String,
    /// Signal direction
    pub direction: SignalDirection,
    /// Confidence level (0.0 - 1.0)
    pub confidence: f64,
    /// Strategy that generated this signal
    pub strategy: String,
    /// Timestamp
    pub timestamp: u64,
}

/// Signal direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalDirection {
    /// Buy signal
    Buy,
    /// Sell signal
    Sell,
    /// Hold/neutral
    Hold,
}

/// Signal engine that processes market data through strategies.
pub struct SignalEngine {
    strategies: Vec<Box<dyn Strategy>>,
    ring_buffer: RingBuffer<Signal, 1024>,
}

impl SignalEngine {
    /// Creates a new signal engine.
    #[must_use]
    pub fn new() -> Self {
        Self {
            strategies: Vec::new(),
            ring_buffer: RingBuffer::new(),
        }
    }

    /// Registers a strategy with the engine.
    pub fn register_strategy(&mut self, strategy: Box<dyn Strategy>) {
        self.strategies.push(strategy);
    }

    /// Processes market data through all strategies.
    ///
    /// Returns signals generated by all strategies.
    pub fn process(&mut self, market_data: &MarketData) -> Vec<Signal> {
        let mut signals = Vec::new();

        for strategy in &self.strategies {
            if let Some(signal) = strategy.evaluate(market_data) {
                let _ = self.ring_buffer.push(signal.clone());
                signals.push(signal);
            }
        }

        signals
    }

    /// Returns the number of registered strategies.
    #[must_use]
    pub fn strategy_count(&self) -> usize {
        self.strategies.len()
    }

    /// Drains pending signals from the internal buffer.
    pub fn drain_signals(&mut self) -> Vec<Signal> {
        let mut signals = Vec::new();
        while let Some(signal) = self.ring_buffer.pop() {
            signals.push(signal);
        }
        signals
    }
}

impl Default for SignalEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestStrategy;

    impl Strategy for TestStrategy {
        fn evaluate(&self, _market_data: &MarketData) -> Option<Signal> {
            Some(Signal {
                symbol: "TEST".to_string(),
                direction: SignalDirection::Buy,
                confidence: 0.8,
                strategy: self.name().to_string(),
                timestamp: 0,
            })
        }

        fn name(&self) -> &str {
            "TestStrategy"
        }
    }

    #[test]
    fn test_signal_engine() {
        let mut engine = SignalEngine::new();
        engine.register_strategy(Box::new(TestStrategy));

        let market_data = MarketData {
            symbol: "TEST".to_string(),
            price: Decimal::from(100),
            volume: Decimal::from(1000),
            timestamp: 0,
        };

        let signals = engine.process(&market_data);
        assert_eq!(signals.len(), 1);
        assert_eq!(signals[0].symbol, "TEST");
    }
}
