name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover-community/elan/master/elan-init.sh -sSf | sh -s --
      - name: Build Lean4 proofs
        run: |
          ~/.elan/bin/lake build
